"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta

import pymysql
pymysql.install_as_MySQLdb()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import mongoengine
from pymongo import MongoClient


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ol9u5si6q9oqve37__xmpwosdla--zjp8(9me_f5!k*u=mqh1p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # custom app
    'testapp',
    'smsroutes',
    'wallet',
    'campaignmanager',
    'analytics',


    # For dbs
    'users',
    'smpp',

    # Third party packages
    'rest_framework',
    'rest_framework_swagger',
    'corsheaders',
    'drf_yasg',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

CORS_ORIGIN_ALLOW_ALL = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'



# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_NAME_MIS',"celetelmissam"),
        'USER': os.environ.get('POSTGRES_USER_MIS',"postgres"),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD_MIS',"admin"),
        'HOST': 'misdb.celetel.com',
        'PORT': 5432,
    },

    'users_db': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_NAME',"celetel"),
        'USER': os.environ.get('POSTGRES_USER',"postgres"),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD',"admin"),
        'HOST': 'userdb.celetel.com',
        'PORT': 5432,
    },

    "smpp_db":{
        'ENGINE': 'django.db.backends.mysql',
        'NAME': "kannel",
        'USER': "root",
        'PASSWORD': "yNLA;auTX1,N",
        'HOST': '43.205.175.234',
        'PORT': '3306',
    },
    
}

# mongoengine.connect(db="sms", host="localhost")
mongoengine.connect(db="sms",host="172.31.42.92",password="celetelsms123",username="root",authentication_source="admin")

# MONGO_CLIENT = MongoClient("localhost")
MONGO_CLIENT = MongoClient("mongodb://root:celetelsms123@172.31.42.92:27017/?authMechanism=DEFAULT")

SMS_DB = MONGO_CLIENT.sms

print("connected to mongoDB")



REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 'rest_framework_simplejwt.authentication.JWTAuthentication',
        'utils.permissions.JWTAuthentication',
    ],
    # 'DEFAULT_PERMISSION_CLASSES':("utils.permissions.IsActiveUser",),
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
    "PERMISSION_CLASS": "utils.permissions.IsActiveUser",
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]

SIMPLE_JWT = {

    'ALGORITHM': 'HS512',
    'SIGNING_KEY': "django-insecure-x1j29^a^y&6x4btc7x^)b3)!1hg^f_!)zkbjm2xy9%e2at&&dg",
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
}
# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'mis/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field


SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'api_key': {
            'type': 'apiKey',
            'in': 'header',
            'name': 'Authorization'
        }
    },
}

DEFAULT_PAGINATION_CLASS=('rest_framework.pagination.LimitOffsetPagination',),
GOOGLE_OAUTH2_CLIENT_ID='53454472905-2ja84e1c9i7rpmg9d4v23l380r47kvt6.apps.googleusercontent.com'


DATABASE_ROUTERS = ["routers.db_routers.usersRouter","routers.db_routers.smppRouter"]
