# Generated by Django 4.0.3 on 2022-10-27 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsSmscroutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smpp_smsc_id', models.IntegerField(unique=True)),
                ('creation_type', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('operator', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.FloatField()),
                ('date', models.DateTimeField()),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('delete', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AccountsSmppusers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smpp_userdetails_id', models.IntegerField(unique=True)),
                ('date', models.DateTimeField()),
                ('on_submit', models.BooleanField(blank=True, null=True)),
                ('sale_price', models.FloatField()),
                ('user', models.IntegerField()),
                ('delete', models.BooleanField(blank=True, default=False, null=True)),
                ('assigned_to', models.IntegerField()),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.accountssmscroutes')),
            ],
        ),
    ]
